export const videoLinks = [
  {
    slug: "dia-1",
    title: "Curso de Algoritmo — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV",
  },
  {
    slug: "dia-2",
    title: "Curso de Algoritmo — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV",
  },
  {
    slug: "dia-3",
    title: "Curso de Algoritmo — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV",
  },
  {
    slug: "dia-4",
    title: "Curso de Algoritmo — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV",
  },
  {
    slug: "dia-5",
    title: "Curso de Algoritmo — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV",
  },
  {
    slug: "dia-6",
    title: "Curso de Algoritmo — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV",
  },
  {
    slug: "dia-7",
    title: "Curso de Algoritmo — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV",
  },
  {
    slug: "dia-8",
    title: "Python Mundo 1 — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dlKP6QQCekuIPky1CiwmdI6",
  },
  {
    slug: "dia-9",
    title: "Python Mundo 1 — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dlKP6QQCekuIPky1CiwmdI6",
  },
  {
    slug: "dia-10",
    title: "Python Mundo 1 — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dlKP6QQCekuIPky1CiwmdI6",
  },
  {
    slug: "dia-11",
    title: "Python Mundo 3 — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH",
  },
  {
    slug: "dia-12",
    title: "Python Mundo 2 — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dm6wYOIW20Nyg12TAjmMGT-",
  },
  {
    slug: "dia-13",
    title: "Python Mundo 3 — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH",
  },
  {
    slug: "dia-14",
    title: "Python Mundo 1 — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dlKP6QQCekuIPky1CiwmdI6",
  },
  {
    slug: "dia-15",
    title: "Curso de MySQL — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dkBs-795Dsgvau_ekxg8g1r",
  },
  {
    slug: "dia-16",
    title: "Curso de MySQL — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dkBs-795Dsgvau_ekxg8g1r",
  },
  {
    slug: "dia-17",
    title: "Curso de MySQL — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dkBs-795Dsgvau_ekxg8g1r",
  },
  {
    slug: "dia-18",
    title: "Curso de MySQL — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dkBs-795Dsgvau_ekxg8g1r",
  },
  {
    slug: "dia-19",
    title: "Curso de MySQL — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dkBs-795Dsgvau_ekxg8g1r",
  },
  {
    slug: "dia-20",
    title: "Curso de MySQL — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dkBs-795Dsgvau_ekxg8g1r",
  },
  {
    slug: "dia-21",
    title: "Curso de MySQL — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dkBs-795Dsgvau_ekxg8g1r",
  },
  {
    slug: "dia-22",
    title: "APIs para iniciantes — Hashtag Programação",
    source: "Hashtag Programação",
    type: "video",
    url: "https://www.youtube.com/@HashtagProgramacao/search?query=API%20python",
  },
  {
    slug: "dia-23",
    title: "Requisições e APIs — Hashtag Programação",
    source: "Hashtag Programação",
    type: "video",
    url: "https://www.youtube.com/@HashtagProgramacao/search?query=requests%20api%20python",
  },
  {
    slug: "dia-24",
    title: "Automação com Python — Hashtag Programação",
    source: "Hashtag Programação",
    type: "video",
    url: "https://www.youtube.com/@HashtagProgramacao/search?query=automa%C3%A7%C3%A3o%20python",
  },
  {
    slug: "dia-25",
    title: "Arquivos com Python — Hashtag Programação",
    source: "Hashtag Programação",
    type: "video",
    url: "https://www.youtube.com/@HashtagProgramacao/search?query=arquivos%20python",
  },
  {
    slug: "dia-26",
    title: "Automação de processos — Hashtag Programação",
    source: "Hashtag Programação",
    type: "video",
    url: "https://www.youtube.com/@HashtagProgramacao/search?query=automa%C3%A7%C3%A3o%20processos%20python",
  },
  {
    slug: "dia-27",
    title: "Projeto prático Python — Hashtag Programação",
    source: "Hashtag Programação",
    type: "video",
    url: "https://www.youtube.com/@HashtagProgramacao/search?query=projeto%20python",
  },
  {
    slug: "dia-28",
    title: "Relatórios com Python — Hashtag Programação",
    source: "Hashtag Programação",
    type: "video",
    url: "https://www.youtube.com/@HashtagProgramacao/search?query=relat%C3%B3rio%20python",
  },
  {
    slug: "dia-29",
    title: "Git e GitHub — Curso em Vídeo",
    source: "Curso em Vídeo",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n",
  },
  {
    slug: "dia-30",
    title: "Publicação de projetos — Hashtag Programação",
    source: "Hashtag Programação",
    type: "video",
    url: "https://www.youtube.com/@HashtagProgramacao/search?query=deploy%20vercel%20github",
  },
];

export function getVideoLinkBySlug(slug: string) {
  return videoLinks.find((video) => video.slug === slug);
}